

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: all_landing_page
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - app-networks

  mydb:
    image: postgres:17.4-alpine3.21
    container_name: landing_page_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=725RA38et
      - POSTGRES_DB=landingpage
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-networks
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_landingpage
    environment:
      PGADMIN_DEFAULT_EMAIL : titumiranan.gtc@gmail.com
      PGADMIN_DEFAULT_PASSWORD : admin123
    ports:
      - "5050:80"
    depends_on:
      - mydb
    restart: always
    networks:
      - app-networks

volumes:
  pgdata:

networks:
  app-networks:
    driver : bridge